seed: 1024
data:
    dataset: anet
    modality: RGB
    num_segments: 8
    seg_length: 1
    batch_size: 32
    workers: 4
    num_classes: 200
    image_tmpl: 'image_{:06d}.jpg'
    val_root: /bpfs/v2_mnt/VIS/wuwenhao/anet
    val_list: 'lists/anet/anet_full_for_zeroshot.txt'
    label_list: 'lists/anet1.3_labels.csv'
    index_bias: 1
    input_size: 224
network:
    arch: ViT-L/14 #ViT-L/14 #ViT-B/32 ViT-B/16
    init: True
    drop_out: 0.0 
    emb_dropout: 0.0 
    type: clip_anet
    sim_header: Transf 
logging:
    print_freq: 10
    eval_freq: 5