resume:
pretrain:
seed: 1024
data:
    dataset: k600
    modality: video
    num_segments: 8
    seg_length: 1
    batch_size: 8
    workers: 4
    num_classes: 160
    image_tmpl: 'img_{:05d}.jpg'
    val_root: '/bpfs/v2_mnt/VIS/wuwenhao/k600_test_video'
    val_list: lists/k600/test_split1_exist.txt
    label_list: lists/k600/k160_labels_split1.csv
    index_bias: 1
    input_size: 224
network:
    arch: ViT-L/14  #ViT-B/32 ViT-B/16
    init: True
    drop_out: 0.0 
    emb_dropout: 0.0 
    type: clip_k600
    sim_header: Transf  
    drop: 0         
logging:
    print_freq: 10
    eval_freq: 1